POST http://localhost:3000/customer HTTP/1.1
content-type: application/json

{
    "name": "John",
    "address": {
        "street": "New Street",
        "number": 101,
        "city": "New City",
        "zip": "10101-101"
    }
}


###

POST http://localhost:3000/customer HTTP/1.1
content-type: application/json

{
    "name": "",
    "address": {
        "street": "New Street",
        "number": 101,
        "city": "New City",
        "zip": "10101-101"
    }
}


###

GET http://localhost:3000/customer HTTP/1.1
content-type: application/json

###


GET http://localhost:3000/customer HTTP/1.1
content-type: application/json
Accept: application/xml

###

POST http://localhost:3000/product HTTP/1.1
content-type: application/json

{
    "type": "B",
    "name": "Product 1",
    "price": 1.01
}

###

GET http://localhost:3000/product HTTP/1.1

###